#This manifest file cotains the resources required to deploy a PostgreSQL database on a kubernetes cluster.
#The resources list contains - Configuration, Persistent Volume, Persistent Volume Claim, Deplyment and Service.
#The database will be accessible on postgres:5432 internally though the service nodes.

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cloudfeeds
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: cloudfeeds
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
    
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: cloudfeeds
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: cloudfeeds
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.5-alpine
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cloudfeeds
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    nodePort: 30000
    protocol: TCP
#    name: postgres
  type: NodePort 
  selector:
    app: postgres
    