#This manifest file defines the resources (Deployment, Service) for Repose External.
#Repose will be exposed on node port 30003 after a successful deployment

# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repose-external
  namespace: cloudfeeds
spec:
  selector:
    matchLabels:
      app: repose-external
  replicas: 1
  template:
    metadata:
      name: repose-external
      labels:
        app: repose-external
    spec:
      containers:
      - name: repose-external
        image: trow.cloudfeeds:31000/cloudfeeds/repose-external:eks
        imagePullPolicy: IfNotPresent
        env: 
        - name: DESTINATION_PORT
          valueFrom: 
            configMapKeyRef:
              name: cloudfeeds-config
              key: destinationPort
        ports:
        - containerPort: 9090

---
# Service 
apiVersion: v1
kind: Service
metadata:
  name: repose-external
  namespace: cloudfeeds
  labels:
    app: repose-external
spec:
  type: NodePort 
  ports:
  - port: 9090
    nodePort: 30003
    protocol: TCP
  selector:
    app: repose-external
